"""
Alpha Protocol Planning Schemas v1
====================================
Versioned schemas for the upfront Senior Planning Gate.
"""

import hashlib
import hmac
import json
import time
import uuid
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator


class SourceEvidence(BaseModel):
    """Evidence retrieved during live planning research."""

    source_type: Literal["url", "github_mcp", "code_review_graph", "memory_graph"]
    reference: str = Field(description="URL, path, or query used")
    publisher: str
    retrieval_time: float
    content_digest: str = Field(pattern=r"^[a-f0-9]{64}$")
    excerpts: list[str] = Field(default_factory=list, description="Bounded excerpts")
    supported_claim_ids: list[str] = Field(default_factory=list)


class ResearchSnapshot(BaseModel):
    """Snapshot of all research context compiled before planning."""

    task_id: str
    project_id: str
    repository_identity: str
    base_sha: str = Field(pattern=r"^[a-f0-9]{40}$")
    request_digest: str = Field(pattern=r"^[a-f0-9]{64}$")
    policy_version: str = "v1"
    retrieval_time: float
    sources: list[SourceEvidence] = Field(default_factory=list)
    unresolved_questions: list[str] = Field(default_factory=list)
    graph_snapshot_digest: str | None = None


class PlanBlueprint(BaseModel):
    """The final consensus plan generated by the Senior Planning Debate."""

    revision_id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    task_id: str
    base_sha: str = Field(pattern=r"^[a-f0-9]{40}$")
    input_request_digest: str
    research_snapshot_digest: str
    
    requirements: list[str]
    alternatives_considered: list[str]
    chosen_design: str
    contracts: list[str] = Field(default_factory=list)
    file_scope: list[str] = Field(default_factory=list)
    dependency_dag_changes: list[str] = Field(default_factory=list)
    gates: list[str] = Field(default_factory=list)
    security_decisions: list[str] = Field(default_factory=list)
    rollback_plan: str | None = None
    token_budgets: dict[str, int] = Field(default_factory=dict)

    def compute_digest(self) -> str:
        # Compute deterministic SHA256 of the blueprint
        data = self.model_dump(mode="json")
        encoded = json.dumps(data, sort_keys=True).encode("utf-8")
        return hashlib.sha256(encoded).hexdigest()


class PlanAssessment(BaseModel):
    """Assessment of a PlanBlueprint by a reviewer (Pro or Opus)."""

    reviewer_principal: str = Field(description="e.g. gemini-3.1-pro-high, claude-opus-4-6-thinking")
    role: Literal["drafting", "critique"]
    plan_digest: str = Field(pattern=r"^[a-f0-9]{64}$")
    verdict: Literal["APPROVE", "REPAIR_REQUIRED", "BLOCKED"]
    findings: str


class PlanningAttestation(BaseModel):
    """Cryptographic attestation authorizing task execution based on a valid plan."""

    purpose: Literal["planning"] = "planning"
    schema_version: Literal["1.0"] = "1.0"
    task_id: str
    project_id: str
    repository_identity: str
    base_sha: str = Field(pattern=r"^[a-f0-9]{40}$")
    blueprint_digest: str = Field(pattern=r"^[a-f0-9]{64}$")
    policy_version: str = "v1"
    
    pro_assessment: PlanAssessment
    opus_assessment: PlanAssessment

    issuer: str = "SYSTEM_SENIOR_PLANNING_ENGINE"
    key_id: str
    issued_at: float
    expires_at: float
    nonce: str = Field(default_factory=lambda: uuid.uuid4().hex)
    signature: str = Field(pattern=r"^[a-f0-9]{64}$")

    @classmethod
    def create(
        cls,
        task_id: str,
        project_id: str,
        repository_identity: str,
        base_sha: str,
        blueprint_digest: str,
        pro_assessment: PlanAssessment,
        opus_assessment: PlanAssessment,
        secret: str,
        key_id: str,
        ttl_seconds: int = 86400 * 7,  # 7 days default expiry
    ) -> "PlanningAttestation":
        if pro_assessment.plan_digest != blueprint_digest or opus_assessment.plan_digest != blueprint_digest:
            raise ValueError("Assessments must match the blueprint digest")
            
        if pro_assessment.verdict != "APPROVE" or opus_assessment.verdict != "APPROVE":
            raise ValueError("Planning Attestation requires unanimous APPROVE verdicts")

        now = time.time()
        nonce = uuid.uuid4().hex
        
        payload = {
            "purpose": "planning",
            "schema_version": "1.0",
            "task_id": task_id,
            "project_id": project_id,
            "repository_identity": repository_identity,
            "base_sha": base_sha,
            "blueprint_digest": blueprint_digest,
            "pro_verdict": pro_assessment.verdict,
            "opus_verdict": opus_assessment.verdict,
            "issued_at": now,
            "expires_at": now + ttl_seconds,
            "nonce": nonce,
            "key_id": key_id,
        }
        
        encoded = json.dumps(payload, sort_keys=True).encode("utf-8")
        signature = hmac.new(secret.encode("utf-8"), encoded, hashlib.sha256).hexdigest()
        
        return cls(
            task_id=task_id,
            project_id=project_id,
            repository_identity=repository_identity,
            base_sha=base_sha,
            blueprint_digest=blueprint_digest,
            pro_assessment=pro_assessment,
            opus_assessment=opus_assessment,
            key_id=key_id,
            issued_at=now,
            expires_at=now + ttl_seconds,
            nonce=nonce,
            signature=signature
        )

    def verify(self, secret: str) -> bool:
        if time.time() > self.expires_at:
            return False
            
        payload = {
            "purpose": self.purpose,
            "schema_version": self.schema_version,
            "task_id": self.task_id,
            "project_id": self.project_id,
            "repository_identity": self.repository_identity,
            "base_sha": self.base_sha,
            "blueprint_digest": self.blueprint_digest,
            "pro_verdict": self.pro_assessment.verdict,
            "opus_verdict": self.opus_assessment.verdict,
            "issued_at": self.issued_at,
            "expires_at": self.expires_at,
            "nonce": self.nonce,
            "key_id": self.key_id,
        }
        encoded = json.dumps(payload, sort_keys=True).encode("utf-8")
        expected = hmac.new(secret.encode("utf-8"), encoded, hashlib.sha256).hexdigest()
        return hmac.compare_digest(self.signature, expected)
